apiVersion: /v1
kind: Service
metadata:
  name: memphis-rest-gateway
  namespace: {{ include "memphis.namespace" . }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.restGateway.port }}
      targetPort: 4444
  selector:
    app: memphis-rest-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memphis-rest-gateway
  namespace: {{ include "memphis.namespace" . }}
  labels:
    app: memphis-rest-gateway
spec:
{{- if eq (include "memphis.clusterEnabled" .) "true" }}
  replicas: 2
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      app: memphis-rest-gateway
  template:
    metadata:
      name: memphis-rest-gateway
      labels:
        app: memphis-rest-gateway
    spec:
      initContainers:
        - name: k8s-busybox-waits4broker
          image: busybox:1.28
          imagePullPolicy: Always
          command: ['sh', '-c', "until nslookup {{ include "memphis.svcName" . }}.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.{{ $.Values.k8sClusterDomain }}; do echo waiting for broker; sleep 2; done"]
      containers:
        - name: memphis-rest-gateway
          image: memphisos/memphis-rest-gateway:master
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 4444
          env:
          - name: ROOT_USER
            value: {{ .Values.restGateway.user | quote }}
          - name: HTTP_PORT
            value: {{ .Values.restGateway.port | quote }}
          - name: MEMPHIS_HOST
            value: {{ include "memphis.svcName" . }}.{{ include "memphis.namespace" . }}.svc.{{ $.Values.k8sClusterDomain }}
          - name: CONNECTION_TOKEN
            valueFrom:
              secretKeyRef:
                name: "memphis-creds"
                key: CONNECTION_TOKEN
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: "memphis-creds"
                key: JWT_SECRET
          - name: REFRESH_JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: "memphis-creds"
                key: REFRESH_JWT_SECRET
          {{- with .Values.memphis.tls }}
          {{ $secretName := tpl .secret.name $ }}
          {{- with .cert }}
          - name: CLIENT_CERT_PATH
            value: "/etc/memphis-certs/clients/{{ $secretName }}/{{ . }}"
          {{- end }}
          {{- with .key }}
          - name: CLIENT_KEY_PATH
            value: "/etc/memphis-certs/clients/{{ $secretName }}/{{ . }}"
          {{- end }}
          {{- with .ca }}
          - name: ROOT_CA_PATH
            value: /etc/memphis-certs/clients/{{ $secretName }}/{{ . }}
          {{- end }}
          volumeMounts:
            - name: {{ $secretName }}-clients-volume
              mountPath: /etc/memphis-certs/clients/{{ $secretName }}
          {{- end }}
         
      {{- with .Values.memphis.tls }}
      {{ $secretName := tpl .secret.name $ }}      
      volumes:
      - name: {{ $secretName }}-clients-volume
        secret:
          secretName: {{ $secretName }}
      {{- end }}
